version: '3'
services: 
  db:
    image: mysql
    restart: always
    environment: 
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DB=${DB_NAME}
    container_name: mysql-db
    volumes:
      - ./pgdata:/var/lib/MYSQLql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-mysql-application:latest
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - DB_TYPE=${DB_TYPE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASS=${DATABASE_PASSWORD}
      - MYSQL_DB=${DB_NAME}
      - MYSQL_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_PORT=${MYSQL_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: nest-todo-app-be
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - MYSQL_ADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - MYSQL_ADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - MYSQL_ADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - db
volumes:
  pgdata:
  pgadmin-data: